/*
 * Generated by Bluespec Compiler, version 2021.07-14-g5f987061 (build 5f987061)
 * 
 * On Tue Nov 16 19:44:59 GMT 2021
 * 
 */
#ifndef __vpi_wrapper_printIPC_h__
#define __vpi_wrapper_printIPC_h__

#include <vpi_user.h>

/* registration function */
void printIPC_vpi_register();

/* VPI wrapper function */
PLI_INT32 printIPC_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_printIPC_h__ */
